name: Deploy Backend to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'primith-app/backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
        
    - name: Build
      run: go build -o main
      working-directory: ./primith-app/backend
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
        JWT_SECRET: ${{ vars.JWT_SECRET }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ vars.JWT_SECRET }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_SSLMODE: ${{ vars.JWT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_DEPLOYMENT_ID: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_ID }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_AI_SEARCH_INDEX: ${{ secrets.AZURE_AI_SEARCH_INDEX }}
        AZURE_AI_SEARCH_ENDPOINT: ${{ secrets.AZURE_AI_SEARCH_ENDPOINT }}
        AZURE_AI_SEARCH_API_KEY: ${{ secrets.AZURE_AI_SEARCH_API_KEY }}
        AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
      with:
        app-name: 'primith-srv'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./primith-app/backend