name: Build and Deploy PDF Table Extract Container

on:
  push:
    branches:
      - master
    paths:
      - 'primith-app/microservices/pdfTableExtract/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: primithcrprod.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./primith-app/microservices/pdfTableExtract
        push: true
        tags: primithcrprod.azurecr.io/pdf-table-extract:latest
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'primith-table-extract'
        publish-profile: ${{ secrets.AZURE_PDF_EXTRACT_PUBLISH_PROFILE }}
        images: 'primithcrprod.azurecr.io/pdf-table-extract:latest'