name: Deploy Table Extract Microservice to Azure

on:
  push:
    branches:
      - master
    paths:
      - 'primith-app/microservices/pdfTableExtract/**'

jobs:
  build_and_deploy_microservice:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Prepare deployment package
      run: |
        # Create deployment directory
        mkdir -p deployment_package
        
        # Copy only necessary files
        cd primith-app/microservices/pdfTableExtract
        cp app.py requirements.txt $GITHUB_WORKSPACE/deployment_package/
        
        # Create startup script
        echo "pip install -r requirements.txt" > $GITHUB_WORKSPACE/deployment_package/startup.sh
        chmod +x $GITHUB_WORKSPACE/deployment_package/startup.sh
        
        # Debug: Show deployment package contents
        echo "Deployment package contents:"
        ls -la $GITHUB_WORKSPACE/deployment_package/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'primth-tbl-extract'
        publish-profile: ${{ secrets.AZURE_PDF_EXTRACT_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/deployment_package
        timeout-in-min: 10